# ------------------------------------------------------------------------------
# Cluster
# ------------------------------------------------------------------------------
# This project runs on OrbStack's built-in Kubernetes, which OrbStack itself
# starts/stops (not something this Makefile provisions). This target only
# waits for it to actually be reachable -- e.g. after `open -a OrbStack` on a
# machine where it was stopped -- rather than assuming `kubectl` already works.
CLUSTER_WAIT_TIMEOUT ?= 60s

# ------------------------------------------------------------------------------
# Istio
# ------------------------------------------------------------------------------
ISTIO_NAMESPACE       ?= istio-system
GATEWAY_API_CRDS_URL  ?= https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml

# ------------------------------------------------------------------------------
# Harbor
# ------------------------------------------------------------------------------
HARBOR_NAMESPACE        ?= harbor
HARBOR_HOST             ?= harbor.k8s.orb.local
HARBOR_CHARTS_PROJECT   ?= charts
# No default on purpose -- a real value here would be a plaintext credential
# committed to git. Pass it on the command line or export it in your shell,
# e.g. `HARBOR_ADMIN_PASSWORD=... make install-harbor`.
HARBOR_ADMIN_PASSWORD   ?=

# ------------------------------------------------------------------------------
# Postgres (standalone infra capability, currently qrcode-api's only consumer)
# ------------------------------------------------------------------------------
POSTGRES_NAMESPACE   ?= postgres
POSTGRES_DEPLOYMENT  ?= qrcode-api-postgres
POSTGRES_DIR         ?= infra/kubernetes/postgres
POSTGRES_SECRET_NAME ?= qrcode-api-postgres-credentials
POSTGRES_USER        ?= qrcode_api
# No default on purpose -- a real value here would be a plaintext credential
# committed to git. Pass it on the command line or export it in your shell,
# e.g. `POSTGRES_PASSWORD=... make install-postgres`. Must match whatever the
# live Postgres role's password actually is (see "ALTER ROLE" if rotating it).
POSTGRES_PASSWORD    ?=
POSTGRES_DB          ?= pix_qrcode
# How long wait-for-postgres blocks before giving up. Postgres is normally up
# in well under a minute; generous because wait-for-postgres runs regardless
# of who created the Deployment (Argo CD or a direct kubectl apply), so it may
# be racing a fresh install rather than checking an already-warm one.
POSTGRES_WAIT_TIMEOUT ?= 180s

# ------------------------------------------------------------------------------
# Forgejo
# ------------------------------------------------------------------------------
FORGEJO_NAMESPACE       ?= forgejo
FORGEJO_HOST            ?= forgejo.k8s.orb.local
FORGEJO_ADMIN_USER      ?= gitea_admin
FORGEJO_GITOPS_REPO_URL ?= http://forgejo-http.forgejo.svc.cluster.local:3000/$(FORGEJO_ADMIN_USER)/k8s-deployment-strategy-gitops.git
# No default on purpose -- a real access token, generated by hand (Forgejo's
# UI has no API for this that doesn't itself need auth): Settings ->
# Applications -> Generate New Token, scope "Specific repositories" -> the
# gitops repo only, permission read:repository only. Regenerated every time
# the cluster (and therefore Forgejo, and every token it ever issued) gets
# reset -- there is no way to make this one persist across that.
FORGEJO_TOKEN           ?=

# ------------------------------------------------------------------------------
# Argo CD
# ------------------------------------------------------------------------------
ARGOCD_NAMESPACE ?= argocd
ARGOCD_HOST      ?= argocd.k8s.orb.local
GITOPS_REPO_DIR  ?= ../k8s-deployment-strategy-gitops

# ------------------------------------------------------------------------------
# Argo Rollouts (manual-fallback install only -- see the "Manual fallback
# installs" section below. Once Argo CD is bootstrapped, this tool is born as
# an Argo CD Application instead; see platform/argo-rollouts/dev/ in the
# gitops repo.)
# ------------------------------------------------------------------------------
ARGO_ROLLOUTS_NAMESPACE ?= argo-rollouts
# Pinned rather than "latest" -- same reasoning as GATEWAY_API_CRDS_URL above,
# so re-running this target later doesn't silently pick up a newer, untested
# controller version.
ARGO_ROLLOUTS_VERSION   ?= v1.10.0
ARGO_ROLLOUTS_INSTALL_URL ?= https://github.com/argoproj/argo-rollouts/releases/download/$(ARGO_ROLLOUTS_VERSION)/install.yaml

# ------------------------------------------------------------------------------
# Prometheus (manual-fallback install only -- see the "Manual fallback
# installs" section below. Once Argo CD is bootstrapped, this tool is born as
# an Argo CD Application instead; see platform/prometheus/dev/ in the gitops
# repo.)
# ------------------------------------------------------------------------------
MONITORING_NAMESPACE     ?= monitoring
# Pinned rather than "latest", same reasoning as ARGO_ROLLOUTS_VERSION above.
PROMETHEUS_CHART_VERSION ?= 88.6.2

# ------------------------------------------------------------------------------
# qrcode-api test-deploy (local smoke-test, not part of GitHub Actions)
# ------------------------------------------------------------------------------
QRCODE_API_NAMESPACE      ?= qrcode-api
QRCODE_API_RELEASE        ?= qrcode-api
QRCODE_API_VALUES         ?= qrcode-api/infra/helm/values.yaml
QRCODE_API_DB_SECRET_NAME ?= qrcode-api-db-credentials

.PHONY: help infra bootstrap-all cluster install-istio install-forgejo install-argocd \
	install-harbor install-postgres install-argo-rollouts install-prometheus

help: ## Show this help message
	@echo "Available targets:"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}'

# ------------------------------------------------------------------------------
# Standard bootstrap chain (disaster-recovery order)
# ------------------------------------------------------------------------------
# Forgejo and Argo CD stay Makefile-imperative permanently, not as a
# transitional step -- structural, not caution: Argo CD can only act once it
# can read the gitops repo, and that repo lives inside Forgejo. Forgejo can't
# be "just another Application" Argo CD creates for itself; that's circular.
#
# Everything else (Harbor, Postgres, Argo Rollouts, Prometheus, qrcode-api) is
# born directly as an Argo CD Application on a clean cluster -- see the
# gitops repo's platform/*/dev/ and apps/*/dev/ directories. The old
# imperative installs for those still exist below as manual fallbacks (a
# reset cluster with no Argo CD in the loop yet, or debugging one tool in
# isolation), but are no longer part of this chain.
#
# Full sequence, most of which can't be a single `make` target because two
# steps are manual and cross-repo (see bootstrap-all's own output):
#   1. cluster
#   2. install-istio
#   3. install-forgejo                  (needs the Gateway for its HTTPRoute)
#   4. MANUAL: recreate the org/repo on Forgejo (public), push
#      k8s-deployment-strategy-gitops to it. No token/credential needed --
#      the repo is public, and Argo CD needs no registered Repository at
#      all to read a public git repo (argocd-repo-credential is a fallback
#      for if that ever changes, not a required step).
#   5. install-argocd                   (needs the Gateway too)
#   6. argocd-harbor-oci-repo           (needed before qrcode-api can sync;
#                                        not in the numbered plan but a real
#                                        dependency traced while building this.
#                                        Also not about auth -- Harbor's
#                                        "charts" project is public too --
#                                        but Argo CD still needs a registered
#                                        Repository to know this OCI host is
#                                        plain HTTP, not HTTPS; see the
#                                        comment on the target itself)
#   7. MANUAL: kubectl apply -f bootstrap/dev-root.yaml (from the gitops repo)
#   8. wait-for-postgres                (Argo CD's Postgres Application must
#                                        have synced by now -- see sync waves
#                                        in the gitops repo)
#   9. prepare-qrcode-api

cluster: ## Wait for the Kubernetes cluster (OrbStack) to be reachable and ready
	@echo "==> Waiting for the cluster to be reachable..."
	@kubectl wait --for=condition=Ready node --all --timeout=$(CLUSTER_WAIT_TIMEOUT)
	@echo "==> Cluster is up:"
	@kubectl get nodes

install-istio: ## Install Istio and the shared *.k8s.orb.local Gateway (idempotent)
	@echo "==> Installing Gateway API CRDs..."
	@kubectl get crd gateways.gateway.networking.k8s.io >/dev/null 2>&1 || \
		kubectl apply -f $(GATEWAY_API_CRDS_URL)
	@echo "==> Creating $(ISTIO_NAMESPACE) namespace..."
	@kubectl create namespace $(ISTIO_NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	@echo "==> Installing Istio via IstioOperator (ambient profile)..."
	@istioctl install -f infra/kubernetes/istio/operator.yaml -y
	@echo "==> Applying the *.k8s.orb.local Gateway (Gateway API, auto-provisions the ingress deployment)..."
	@kubectl apply -k infra/kubernetes/istio
	@echo "==> Waiting for the istio-gateway-istio deployment to become available..."
	@kubectl rollout status deployment/istio-gateway-istio \
		--namespace $(ISTIO_NAMESPACE) --timeout=300s
	@echo "==> Istio ingress gateway is up. Service:"
	@kubectl get svc istio-gateway-istio --namespace $(ISTIO_NAMESPACE)

install-forgejo: ## Install Forgejo (Git hosting) at http://$(FORGEJO_HOST) via the shared Gateway (idempotent)
	@echo "==> Creating $(FORGEJO_NAMESPACE) namespace..."
	@kubectl create namespace $(FORGEJO_NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	@echo "==> Installing/upgrading Forgejo via Helm..."
	@echo "    Exposed as a ClusterIP Service ('forgejo-http'), reached via an HTTPRoute on the"
	@echo "    shared istio-gateway at http://$(FORGEJO_HOST) -- not its own LoadBalancer, for the"
	@echo "    same port-80 scheduling conflict reason noted by the harbor target above."
	@echo "    gitea.config.server.ROOT_URL set explicitly -- the chart's own httpRoute.enabled"
	@echo "    would derive this automatically, but this project manages Forgejo's HTTPRoute"
	@echo "    itself (infra/kubernetes/forgejo/), not via the chart, so it's left at its"
	@echo "    unconfigured default (http://git.example.com/) unless set here. Without this,"
	@echo "    Forgejo shows a ROOT_URL-mismatch warning and some app features misbehave"
	@echo "    (redirects, webhook URLs, clone command hints) since they'd all point at"
	@echo "    git.example.com instead of the real hostname."
	@helm upgrade --install forgejo oci://code.forgejo.org/forgejo-helm/forgejo \
		--namespace $(FORGEJO_NAMESPACE) \
		--set service.http.type=ClusterIP \
		--set gitea.config.server.ROOT_URL=http://$(FORGEJO_HOST) \
		--wait --timeout 10m
	@echo "==> Applying Forgejo's HTTPRoute on the shared Gateway..."
	@kubectl apply -k infra/kubernetes/forgejo
	@echo "==> Waiting for the forgejo deployment to become available..."
	@kubectl rollout status deployment/forgejo \
		--namespace $(FORGEJO_NAMESPACE) --timeout=300s
	@echo "==> Forgejo is up at http://$(FORGEJO_HOST)"
	@echo "    NEXT (manual, cross-repo, unavoidable): recreate the org/repo, generate a fresh"
	@echo "    access token (Settings -> Applications -> Generate New Token, scope 'Specific"
	@echo "    repositories' -> this repo only, read:repository only), and push"
	@echo "    k8s-deployment-strategy-gitops to it. See bootstrap-all's output for the full"
	@echo "    remaining sequence."

install-argocd: ## Install Argo CD (GitOps controller) at http://$(ARGOCD_HOST) via the shared Gateway (idempotent)
	@echo "==> Creating $(ARGOCD_NAMESPACE) namespace..."
	@kubectl create namespace $(ARGOCD_NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	@echo "==> Installing/upgrading Argo CD via Helm..."
	@echo "    Server runs in insecure/plain-HTTP mode (configs.params.\"server.insecure\") since it"
	@echo "    sits behind the same TLS-less Gateway as everything else in this cluster. Exposed as"
	@echo "    a ClusterIP Service ('argocd-server'), reached via an HTTPRoute -- not its own"
	@echo "    LoadBalancer, for the same port-80 scheduling conflict reason noted by harbor above."
	@helm upgrade --install argocd oci://ghcr.io/argoproj/argo-helm/argo-cd \
		--namespace $(ARGOCD_NAMESPACE) \
		--set 'configs.params.server\.insecure=true' \
		--wait --timeout 10m
	@echo "==> Applying Argo CD's HTTPRoute on the shared Gateway..."
	@kubectl apply -k infra/kubernetes/argocd
	@echo "==> Waiting for the argocd-server deployment to become available..."
	@kubectl rollout status deployment/argocd-server \
		--namespace $(ARGOCD_NAMESPACE) --timeout=300s
	@echo "==> Argo CD is up at http://$(ARGOCD_HOST) (user: admin)"
	@echo "    Initial password: kubectl -n $(ARGOCD_NAMESPACE) get secret argocd-initial-admin-secret -o jsonpath='{.data.password}' | base64 -d"

# Still needed even though Harbor's "charts" project is public: this isn't
# about authentication (no username/password below -- none needed for an
# anonymous-pull public project), it's about protocol. Harbor here serves
# plain HTTP, not HTTPS, and insecureOCIForceHttp is only settable on a
# registered Repository -- there's no per-Application, inline way to tell
# Argo CD "this OCI host is http, not https" (verified against Argo CD's
# declarative-setup docs: url/type/enableOCI are the only required fields
# on the Repository Secret, username/password are optional extras, and
# protocol/TLS config lives exclusively at this level, never on a source).
# Without this, Argo CD assumes HTTPS and qrcode-api's chart source fails.
argocd-harbor-oci-repo: ## Register Harbor's OCI charts registry as an Argo CD Repository (idempotent; needed before qrcode-api can sync, even though the project is public -- see comment above)
	@echo "==> Registering Harbor's OCI charts registry as an Argo CD Repository..."
	@echo "    No username/password -- the 'charts' project is public, anonymous pull. This"
	@echo "    only exists to set insecureOCIForceHttp=true (plain HTTP, not HTTPS), which has"
	@echo "    no per-Application equivalent and must be declared on a registered Repository."
	@kubectl create secret generic harbor-charts-oci-repo \
		--namespace $(ARGOCD_NAMESPACE) \
		--from-literal=type=helm \
		--from-literal=name=harbor-charts \
		--from-literal=url=$(HARBOR_HOST)/$(HARBOR_CHARTS_PROJECT) \
		--from-literal=enableOCI=true \
		--from-literal=insecureOCIForceHttp=true \
		--dry-run=client -o yaml \
		| kubectl label --local -f - argocd.argoproj.io/secret-type=repository -o yaml \
		| kubectl apply -f -
	@echo "==> Repository credential registered: $(HARBOR_HOST)/$(HARBOR_CHARTS_PROJECT)"

bootstrap-all: cluster install-istio install-forgejo install-argocd ## Chain everything that CAN be chained; print the manual cross-repo steps that can't be
	@echo ""
	@echo "==================================================================="
	@echo " Automated part done: cluster, Istio, Forgejo, Argo CD are up."
	@echo " The rest can't be chained here -- two steps are manual and"
	@echo " cross-repo (this repo can't push to Forgejo or apply into the"
	@echo " gitops repo's own bootstrap file on your behalf). Do these next,"
	@echo " in order:"
	@echo "==================================================================="
	@echo ""
	@echo "1. MANUAL -- recreate the org/repo on Forgejo (http://$(FORGEJO_HOST)) as PUBLIC, then"
	@echo "   push the gitops repo to it:"
	@echo "     cd $(GITOPS_REPO_DIR) && git push http://$(FORGEJO_ADMIN_USER)@$(FORGEJO_HOST)/$(FORGEJO_ADMIN_USER)/k8s-deployment-strategy-gitops.git main"
	@echo "   No access token needed for this: Argo CD requires no registered Repository at all"
	@echo "   to read a public git repo (anonymous clone/fetch just works). If the repo is ever"
	@echo "   made private instead, use 'make argocd-repo-credential FORGEJO_TOKEN=...' first."
	@echo ""
	@echo "2. make argocd-harbor-oci-repo   (needed before qrcode-api can sync -- not about auth,"
	@echo "   Harbor's charts project is public too, but Argo CD still needs to be told this"
	@echo "   OCI host is plain HTTP, which only a registered Repository can express)"
	@echo ""
	@echo "3. MANUAL -- from the gitops repo, create the App-of-Apps root (the one Application"
	@echo "   Argo CD can never discover on its own, since nothing points at it yet):"
	@echo "     kubectl apply -f $(GITOPS_REPO_DIR)/bootstrap/dev-root.yaml"
	@echo "   From this point on, Argo CD sees and acts on everything declared in that repo."
	@echo ""
	@echo "4. make wait-for-postgres"
	@echo "   make prepare-qrcode-api POSTGRES_PASSWORD=<...>"
	@echo ""
	@echo "   (qrcode-api's Argo CD Application depends on this Secret existing, and on Argo"
	@echo "   Rollouts' CRDs already being registered -- both handled by sync-wave ordering"
	@echo "   declared in the gitops repo once dev-root is applied in step 3.)"

# ------------------------------------------------------------------------------
# Manual fallback installs (Harbor, Postgres, Argo Rollouts, Prometheus)
# ------------------------------------------------------------------------------
# NOT part of the standard bootstrap chain above. On a normal disaster
# recovery, these four are born as Argo CD Applications instead (see the
# gitops repo's platform/*/dev/application.yaml files) once dev-root is
# applied -- no adoption dance needed on a clean cluster, since there's no
# live state to reconcile against.
#
# Kept here, clearly separated, as manual fallbacks: useful if you need one
# of these tools running with no Argo CD in the loop at all (debugging a tool
# in isolation, or Argo CD itself being down/not yet bootstrapped).

install-harbor: ## MANUAL FALLBACK (not part of standard bootstrap): install Harbor directly via Helm (idempotent)
	@if [ -z "$(HARBOR_ADMIN_PASSWORD)" ]; then \
		echo "HARBOR_ADMIN_PASSWORD must be set (no default -- see the comment by its declaration)."; \
		exit 1; \
	fi
	@echo "==> Adding/updating the Harbor Helm repo..."
	@helm repo add harbor https://helm.goharbor.io >/dev/null 2>&1 || true
	@helm repo update harbor >/dev/null
	@echo "==> Creating $(HARBOR_NAMESPACE) namespace..."
	@kubectl create namespace $(HARBOR_NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	@echo "==> Installing/upgrading Harbor via Helm..."
	@echo "    Exposed as a ClusterIP Service named 'harbor', reached via an HTTPRoute on the"
	@echo "    shared istio-gateway at http://$(HARBOR_HOST) -- not its own LoadBalancer. A"
	@echo "    single-node cluster only has one host port 80 to hand out via k3s's ServiceLB,"
	@echo "    and qrcode-api's Gateway needs it too; only one LoadBalancer:80 can ever bind."
	@helm upgrade --install harbor harbor/harbor \
		--namespace $(HARBOR_NAMESPACE) \
		--set expose.type=clusterIP \
		--set expose.clusterIP.name=harbor \
		--set expose.tls.enabled=false \
		--set externalURL=http://$(HARBOR_HOST) \
		--set harborAdminPassword=$(HARBOR_ADMIN_PASSWORD) \
		--wait --timeout 10m
	@echo "==> Applying Harbor's HTTPRoute on the shared Gateway..."
	@kubectl apply -k infra/kubernetes/harbor
	@echo "==> Harbor is up at http://$(HARBOR_HOST) (user: admin)"

install-postgres: ## MANUAL FALLBACK (not part of standard bootstrap): install Postgres directly via kubectl (idempotent)
	@if [ -z "$(POSTGRES_PASSWORD)" ]; then \
		echo "POSTGRES_PASSWORD must be set (no default -- see the comment by its declaration)."; \
		exit 1; \
	fi
	@echo "==> Creating $(POSTGRES_NAMESPACE) namespace..."
	@kubectl create namespace $(POSTGRES_NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	@echo "==> Creating/updating the Postgres credentials Secret..."
	@kubectl create secret generic $(POSTGRES_SECRET_NAME) \
		--namespace $(POSTGRES_NAMESPACE) \
		--from-literal=POSTGRES_USER=$(POSTGRES_USER) \
		--from-literal=POSTGRES_PASSWORD=$(POSTGRES_PASSWORD) \
		--from-literal=POSTGRES_DB=$(POSTGRES_DB) \
		--dry-run=client -o yaml | kubectl apply -f -
	@echo "==> Applying Postgres manifests from $(POSTGRES_DIR)..."
	@kubectl apply -f $(POSTGRES_DIR)
	@$(MAKE) wait-for-postgres
	@echo "==> Postgres is up in namespace $(POSTGRES_NAMESPACE)."

install-argo-rollouts: ## MANUAL FALLBACK (not part of standard bootstrap): install Argo Rollouts directly via kubectl (idempotent)
	@echo "==> Creating $(ARGO_ROLLOUTS_NAMESPACE) namespace..."
	@kubectl create namespace $(ARGO_ROLLOUTS_NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	@echo "==> Installing the Argo Rollouts controller + CRDs ($(ARGO_ROLLOUTS_VERSION))..."
	@echo "    Raw manifest, not the argo-helm chart -- the project's own docs only document"
	@echo "    'kubectl apply -f install.yaml' as the install path; Helm isn't mentioned as an"
	@echo "    alternative there, unlike Argo CD's docs which do point at argo-helm."
	@echo "    --server-side because the Rollout/AnalysisRun CRDs' schemas exceed the 256KiB"
	@echo "    last-applied-configuration annotation limit that plain client-side apply hits."
	@kubectl apply --server-side -n $(ARGO_ROLLOUTS_NAMESPACE) -f $(ARGO_ROLLOUTS_INSTALL_URL)
	@echo "==> Registering the Gateway API traffic-routing plugin (argoproj-labs/gatewayAPI)"
	@echo "    and its supplemental RBAC (HTTPRoutes aren't covered by the core install)..."
	@echo "    --server-side, and under a distinct --field-manager: argo-rollouts-config is"
	@echo "    co-owned with the install.yaml above. Client-side apply's diff-and-strip logic"
	@echo "    drops fields (e.g. labels) it doesn't know the other manifest declared; a shared"
	@echo "    server-side field-manager name has the same problem (whichever applies last wins"
	@echo "    and prunes the other's fields), so this uses its own field-manager identity."
	@kubectl apply --server-side --field-manager=argo-rollouts-gatewayapi-plugin \
		-k infra/kubernetes/argo-rollouts
	@echo "==> Restarting the controller so it picks up the plugin config..."
	@kubectl rollout restart deployment/argo-rollouts --namespace $(ARGO_ROLLOUTS_NAMESPACE)
	@echo "==> Waiting for the argo-rollouts deployment to become available..."
	@kubectl rollout status deployment/argo-rollouts \
		--namespace $(ARGO_ROLLOUTS_NAMESPACE) --timeout=300s
	@echo "==> Argo Rollouts is up in namespace $(ARGO_ROLLOUTS_NAMESPACE)."

install-prometheus: ## MANUAL FALLBACK (not part of standard bootstrap): install Prometheus directly via Helm (idempotent)
	@echo "==> Adding/updating the prometheus-community Helm repo..."
	@helm repo add prometheus-community https://prometheus-community.github.io/helm-charts >/dev/null 2>&1 || true
	@helm repo update prometheus-community >/dev/null
	@echo "==> Creating $(MONITORING_NAMESPACE) namespace..."
	@kubectl create namespace $(MONITORING_NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	@echo "==> Installing/upgrading kube-prometheus-stack via Helm..."
	@echo "    Grafana and Alertmanager disabled -- this pass only needs Prometheus itself to"
	@echo "    explore/query metrics for the Argo Rollouts AnalysisTemplate. ClusterIP, no"
	@echo "    HTTPRoute -- port-forward for now (kubectl -n $(MONITORING_NAMESPACE) port-forward"
	@echo "    svc/prometheus-kube-prometheus-prometheus 9090:9090)."
	@helm upgrade --install prometheus prometheus-community/kube-prometheus-stack \
		--namespace $(MONITORING_NAMESPACE) \
		--version $(PROMETHEUS_CHART_VERSION) \
		--set grafana.enabled=false \
		--set alertmanager.enabled=false \
		--set prometheus.service.type=ClusterIP \
		--wait --timeout 10m
	@echo "==> Applying the istio-gateway PodMonitor..."
	@echo "    Confirmed empirically that this is required, not optional: the shared Gateway"
	@echo "    already carries Istio's own prometheus.io/scrape annotations (metrics-merge"
	@echo "    endpoint at :15020/stats/prometheus), but kube-prometheus-stack's Prometheus"
	@echo "    Operator-managed Prometheus only discovers targets via PodMonitor/ServiceMonitor"
	@echo "    CRDs -- those legacy annotations alone got nothing scraped. A PodMonitor (not"
	@echo "    ServiceMonitor) is needed too: the Gateway's own Service doesn't expose port"
	@echo "    15020 at all, only 15021 (status) and 80 (http)."
	@kubectl apply -k infra/kubernetes/prometheus
	@echo "==> Prometheus is up in namespace $(MONITORING_NAMESPACE)."

infra: install-istio install-harbor install-postgres install-forgejo install-argocd install-argo-rollouts install-prometheus ## Old-style, all-imperative install (pre-GitOps). Prefer bootstrap-all + Argo CD-born Applications instead.

# ------------------------------------------------------------------------------
# qrcode-api test-deploy (local smoke-test, not part of GitHub Actions)
# ------------------------------------------------------------------------------
# The base-webapp chart itself no longer lives in this repo -- it was extracted
# to its own repo (helm-chart-base) so its source, versioning, and publishing
# are maintained independently of this monorepo. package-chart/publish-chart/
# verify-chart-published/harbor-chart-project moved there with it (see that
# repo's own Makefile). This target now pulls the chart the same way Argo CD
# does downstream: a pinned, published OCI artifact from Harbor, not a local
# path -- so this smoke-test target keeps working with nothing local to point
# it at anymore.
QRCODE_API_CHART_REF     ?= oci://$(HARBOR_HOST)/$(HARBOR_CHARTS_PROJECT)/base-webapp
QRCODE_API_CHART_VERSION ?= 0.7.2

# Kubernetes Secrets are namespace-scoped: qrcode-api's pod (namespace
# qrcode-api) can't reference the Postgres Secret living in namespace
# postgres, so it needs its own copy of the same credential here.
.PHONY: wait-for-postgres prepare-qrcode-api qrcode-api

wait-for-postgres: ## Wait for Postgres to be ready, regardless of what created it (Argo CD or a direct apply)
	@echo "==> Waiting for $(POSTGRES_DEPLOYMENT) to become available in $(POSTGRES_NAMESPACE)..."
	@echo "    kubectl wait only looks at current state, not provenance -- this synchronizes"
	@echo "    with Postgres being ready whether Argo CD or 'make install-postgres' produced it."
	@kubectl wait --for=condition=Available deployment/$(POSTGRES_DEPLOYMENT) \
		--namespace $(POSTGRES_NAMESPACE) --timeout=$(POSTGRES_WAIT_TIMEOUT)
	@echo "==> Postgres is ready."

prepare-qrcode-api: wait-for-postgres ## Create the qrcode-api namespace + its DB credentials Secret (depends on Postgres being up)
	@if [ -z "$(POSTGRES_PASSWORD)" ]; then \
		echo "POSTGRES_PASSWORD must be set (same value used for Postgres's own credentials)."; \
		exit 1; \
	fi
	@echo "==> Creating $(QRCODE_API_NAMESPACE) namespace..."
	@kubectl create namespace $(QRCODE_API_NAMESPACE) --dry-run=client -o yaml | kubectl apply -f -
	@kubectl label namespace $(QRCODE_API_NAMESPACE) istio.io/dataplane-mode=ambient --overwrite
	@echo "==> Creating/updating qrcode-api's DB credentials Secret..."
	@echo "    Never GitOps-managed -- a real credential, created here the same way it always"
	@echo "    has been. Must match a Postgres role that only exists once Postgres is actually"
	@echo "    up, hence the dependency on wait-for-postgres."
	@kubectl create secret generic $(QRCODE_API_DB_SECRET_NAME) \
		--namespace $(QRCODE_API_NAMESPACE) \
		--from-literal=DB_USERNAME=$(POSTGRES_USER) \
		--from-literal=DB_PASSWORD=$(POSTGRES_PASSWORD) \
		--dry-run=client -o yaml | kubectl apply -f -
	@echo "==> Namespace and Secret ready. qrcode-api's Argo CD Application can now sync."

qrcode-api: install-postgres prepare-qrcode-api ## Deploy qrcode-api (base-webapp chart, pulled from Harbor) to the local cluster for smoke-testing
	@echo "==> Installing/upgrading the qrcode-api release from $(QRCODE_API_CHART_REF):$(QRCODE_API_CHART_VERSION)..."
	@helm upgrade --install $(QRCODE_API_RELEASE) $(QRCODE_API_CHART_REF) \
		--version $(QRCODE_API_CHART_VERSION) \
		--plain-http \
		--namespace $(QRCODE_API_NAMESPACE) \
		-f $(QRCODE_API_VALUES) \
		--wait --timeout 5m
	@echo "==> Deployed. Try:"
	@echo "    kubectl get pods -n $(QRCODE_API_NAMESPACE)"
	@echo "    kubectl get httproute -n $(QRCODE_API_NAMESPACE)"
	@echo "    curl http://qrcode-api.k8s.orb.local/actuator/health"
