{{- if .Values.httpRoute.enabled -}}
{{- $fullName := include "base-webapp.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $hostnames := .Values.httpRoute.hostnames -}}
{{- if not $hostnames -}}
{{- $hostnames = list (printf "%s.%s" $fullName .Values.httpRoute.domain) -}}
{{- end -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "base-webapp.labels" . | nindent 4 }}
  {{- with .Values.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- with .Values.httpRoute.parentRefs }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  hostnames:
    {{- toYaml $hostnames | nindent 4 }}
  rules:
    {{- range .Values.httpRoute.rules }}
    {{- with .matches }}
    - matches:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .filters }}
      filters:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      backendRefs:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
          weight: 1
    {{- end }}
{{- end }}
