apiVersion: v1
kind: Service
metadata:
  name: qrcode-api-postgres
  namespace: qrcode-api
spec:
  type: ClusterIP
  selector:
    app: qrcode-api-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
